In [2]:
import numpy as np
#length of classrooms
len_m = (10,11,12,13,14,15,16,17,18,19)

len_np= np.array(len_m)
len_np

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [3]:
#width of classrooms
wid_m = (11,12,27,13,14,15,16,17,18,22)

wid_np= np.array(wid_m)
wid_np

array([11, 12, 27, 13, 14, 15, 16, 17, 18, 22])

In [4]:
#height of classrooms
ht_m = (11,12,27,13,14,15,16,17,18,22)

ht_np= np.array(ht_m)
ht_np

array([11, 12, 27, 13, 14, 15, 16, 17, 18, 22])

In [5]:
volume = len_np*wid_np*ht_np
volume

array([1210, 1584, 8748, 2197, 2744, 3375, 4096, 4913, 5832, 9196])