In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


'C:\Users\Sap\anaconda3\New' is not recognized as an internal or external command,
operable program or batch file.


In [3]:
conda install numpy


Note: you may need to restart the kernel to use updated packages.



EnvironmentLocationNotFound: Not a conda environment: C:\Users\Sap\anaconda3\New



In [5]:
import numpy as np

In [6]:
from numpy import random
x= random.randint(50,size=(10))
print(x)

[ 0 29 26 44 13 32 19 15 17  1]


In [7]:
from numpy import random
x= random.randint(50,size=(3,5))
print(x)

[[21 22 46 44 28]
 [35 47 39 41 28]
 [21 37 20 17 44]]


In [9]:
from numpy import random
x= random.randint(50,size=(3,5))
print(x)

[[19 49  4 24 14]
 [35 49 44  6  8]
 [34 29 21 49  7]]


In [15]:
from numpy import random
random.seed(101)
x= random.randint(100,size=(3,5))
print(x)

[[95 11 81 70 63]
 [87 75  9 77 40]
 [ 4 63 40 60 92]]


# # creating vactor as numpy

In [16]:
list1=[1,2,3]

list2= [[10],[20],[30]]

vector1 = np.array(list1)
vector2 = np.array(list2)
print("horizontal vector")
print(vector1)
print("-----------")
print("vertical vector")
print(vector2)

horizontal vector
[1 2 3]
-----------
vertical vector
[[10]
 [20]
 [30]]


# # practical creating matrix in numpy

In [23]:
a=np.matrix('1,2;3,4')
print(a)
b= np.matrix([[5,6,7],[4,6]])
print("\n",b)

[[1 2]
 [3 4]]

 [[list([5, 6, 7]) list([4, 6])]]


# # matrix multiplication

In [24]:
A = 5

B = [[6,7],[8,9]]
print(np.dot(A,B))

[[30 35]
 [40 45]]


In [25]:
A = [[6,7],
     [8,9]]
B = [[1,2],
     [3,4]]
print(np.dot(A,B))

[[27 40]
 [35 52]]


In [26]:
A = ([1,4,7],[2,3,5],[8,9,10])
np.transpose(A)

array([[ 1,  2,  8],
       [ 4,  3,  9],
       [ 7,  5, 10]])

# # percentile and interquartile in numpy

In [4]:
import numpy as np
data = [21,25,69,45,54,78,98,56,23,54,78,24,25,26,21,23,12,45,78,45]

#first quartile(Q1)

Q1 = np.median(data[:10])
print(Q1)

#third quartile(Q1)

Q3 = np.median(data[10:])
print(Q3)

54.0
25.5


# # array broadcasting

In [5]:
a = np.array([1.0,2.0,3.0])
b = np.array([2.0,2.0,2.0])

a*b

array([2., 4., 6.])

In [7]:
a = np.array([1.0,2.0,3.0])
b = 2.1

a*b

array([2.1, 4.2, 6.3])

# # calculate BMI of cricketplayes

In [12]:
#Heights of playes
import numpy as np
hg_in = [61,65,64,69,70,68,64,63,62,66,72]
#convert into numpy array

ht_np = np.array(hg_in)

#convert height from inch to meter to meter by exposing it to 0.0245

ht_np = ht_np*0.0245
ht_np

array([1.4945, 1.5925, 1.568 , 1.6905, 1.715 , 1.666 , 1.568 , 1.5435,
       1.519 , 1.617 , 1.764 ])

In [13]:
#weight of playes in pound

wt_pd = [100,200,160,150,180,147,157,158,161,149,163]

#convert into numpy array
wt_np = np.array(wt_pd)
#convert height from inch to meter to meter by exposing it to 0.0245

wt_np = wt_np*0.45
wt_np

array([45.  , 90.  , 72.  , 67.5 , 81.  , 66.15, 70.65, 71.1 , 72.45,
       67.05, 73.35])

In [14]:
BMI = wt_np/(ht_np**2)
BMI

array([20.1474773 , 35.48817184, 29.28467305, 23.61964808, 27.5395456 ,
       23.83306264, 28.73558543, 29.84395202, 31.39950792, 25.64358515,
       23.57235411])

In [15]:
BMI[-1]

23.572354111712713

In [16]:
players = np.array([wt_np,ht_np])
players

array([[45.    , 90.    , 72.    , 67.5   , 81.    , 66.15  , 70.65  ,
        71.1   , 72.45  , 67.05  , 73.35  ],
       [ 1.4945,  1.5925,  1.568 ,  1.6905,  1.715 ,  1.666 ,  1.568 ,
         1.5435,  1.519 ,  1.617 ,  1.764 ]])

In [17]:
players[0][2]

72.0

In [18]:
players[0][0]

45.0

In [20]:
players[1][0]

1.4945000000000002

In [21]:
players[1]

array([1.4945, 1.5925, 1.568 , 1.6905, 1.715 , 1.666 , 1.568 , 1.5435,
       1.519 , 1.617 , 1.764 ])

In [22]:
#transpose

pT = players.transpose()
pT

array([[45.    ,  1.4945],
       [90.    ,  1.5925],
       [72.    ,  1.568 ],
       [67.5   ,  1.6905],
       [81.    ,  1.715 ],
       [66.15  ,  1.666 ],
       [70.65  ,  1.568 ],
       [71.1   ,  1.5435],
       [72.45  ,  1.519 ],
       [67.05  ,  1.617 ],
       [73.35  ,  1.764 ]])

In [23]:
#statistical and mathematical function on players data

print(np.mean(wt_np))

70.56818181818181


In [24]:
#statistical and mathematical function on players data

print(np.median(wt_np))

71.10000000000001


In [26]:
#statistical and mathematical function on players data

print(np.sum(wt_np))
print(np.std(wt_np))
print(np.corrcoef(wt_np,ht_np))

776.25
10.423231760379238
[[1.         0.35546304]
 [0.35546304 1.        ]]


## calculation of volume of campus classrooms



In [1]:
import numpy as np
#length of classrooms
len_m = [10,11,12,13,14,15,16,17,18,19]

len_np= np.array(len_m)
len_np

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [2]:
#width of classrooms
wid_m = [11,12,27,13,14,15,16,17,18,22]

wid_np= np.array(wid_m)
wid_np

array([11, 12, 27, 13, 14, 15, 16, 17, 18, 22])

In [3]:
#height of classrooms
ht_m = [11,12,27,13,14,15,16,17,18,22]

ht_np= np.array(ht_m)
ht_np

array([11, 12, 27, 13, 14, 15, 16, 17, 18, 22])

In [4]:
volume = len_np*wid_np*ht_np
volume

array([1210, 1584, 8748, 2197, 2744, 3375, 4096, 4913, 5832, 9196])